language: objective-c

before_install:
    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent
    
script:
    - xctool -project Routelandia.xcodeproj -scheme Routelandia -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - xctool test -project Routelandia.xcodeproj -scheme RoutelandiaTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
    slack: psu2014:d813kB383u88FUQ81iW3OHZs